name: Barotraumix
recipe: drupal9
config:
  webroot: web
  via: nginx
services:
  appserver:
    overrides:
#     Default Lando image with SteamCMD.
      image: azumasv/barotraumix:lando-php-8.1
      environment:
        BAROTRAUMA_SOURCE_FILES: "sites/default/barotrauma"
